version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: usuario
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-usuario:5432/db_usuario
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "false"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      JWT_SECRET: MinhaChaveSuperSecretaComMaisDe256BitsParaSerSeguraEValidaNoHS256Algorithm
      JWT_EXPIRATION: 3600000
    depends_on:
      - db-usuario

  db-usuario:
    image: postgres:15.3
    container_name: db-usuario
    restart: always
    environment:
      POSTGRES_DB: db_usuario
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
