# Nome da aplicação
spring.application.name=usuario

# Configuração do banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/db_usuario
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT (?? USAR A MESMA em todos os microsserviços!)
jwt.secret=MinhaChaveSuperSecretaComMaisDe256BitsParaSerSeguraEValidaNoHS256Algorithm
jwt.expiration=3600000

# Porta do serviço usuário
server.port=8080

# Logs
logging.level.com.javanauta.usuario=INFO
logging.level.org.springframework.security=DEBUG

# URL base para o Feign Client ViaCep
viacep.url=https://viacep.com.br
